### PR TITLE
velero konveyor-dev rebase Sept 19, 2024

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Review by shubham-pampattiwar — DISMISSED** [review]

**Comment by mateusoliveira43** [comment]
All non block datamover E2E tests failed. Any idea why?

**Comment by kaovilai** [comment]
> All non block datamover E2E tests failed. Any idea why?

https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1726778575179739

**Pull request merged**
