### PR TITLE
[oadp-1.3] crd and go.mod updates for velero 1.12.4

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]
/lgtm

**Comment by mateusoliveira43** [comment]
/hold
just for the other PR to merge first

**Review by rayfordj — APPROVED** [review]
/lgtm

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by weshayutin** [comment]
@sseago @mpryc @mateusoliveira43 FYI... real failure here, do not override.
All three failures on:
```
[FAIL] Subscription Config Suite Test Proxy test table [It] HTTP_PROXY set
```

**Comment by kaovilai** [comment]
/override ci/prow/4.13-e2e-test-azure
also failed on NO_PROXY

**Pull request merged**
