### PR TITLE
Redirect customers and partners to open issues and bugs in jira via the bug template

### PR DESCRIPTION
**Pull request by weshayutin**
we need to try and prevent customers, gss and partners from opening bugs in github.

### CODE REVIEW

**Comment by kaovilai** [comment]
Need to note where to GSS/Partner file bugs and customers contact GSS to file bugs for them.

**Comment by weshayutin** [comment]
> Need to note where to GSS/Partner file bugs and customers contact GSS to file bugs for them.

tracking has moved to [jira](https://issues.redhat.com/projects/OADP/issues)

**Comment by weshayutin** [comment]
Screenshot-20220627111943-1610x872

I forced push to my fork https://github.com/weshayutin/oadp-operator/issues ( try it )

**Pull request merged**
