### PR TITLE
[oadp-1.3] feat: Add golangci-lint linters - imports (#1337)

### PR DESCRIPTION
**Pull request by mateusoliveira43**
* feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

* fixup! feat: Add golangci-lint

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>

---------

Signed-off-by: Mateus Oliveira <msouzaol@redhat.com>
(cherry picked from commit 76f0049ebe2dd3cb4e5ed710553d76323a8f236b)

### CODE REVIEW

**Comment by weshayutin** [comment]
let's not backport, let's do this across the main/default branches only until it's consistent across repos

**Comment by mateusoliveira43** [comment]
Closing as I already had to resolve conflicts in https://github.com/openshift/oadp-operator/pull/1356

**Pull request closed without merging**
