### PR TITLE
CI: Search virtualization package manifest for stable channel.

### PR DESCRIPTION
**Pull request by mrnold**
## Why the changes were made

Fixes virtualization CI failures with operator versions like 4.99.0-0.1713770549. The operator installation code only looked at the first channel in the package manifest, which is sometimes "dev-preview" instead of "stable". This change looks explicitly for "stable".  

## How to test the changes made

Run virtualization E2E tests against a cluster with this condition. It should fail without the fix, and proceed when the fix is applied.

### CODE REVIEW

**Review by weshayutin — COMMENTED** [review]
NICE! Thank you @mrnold

**Review by mateusoliveira43 — APPROVED** [review]
All beforeAll jobs for virt passed

:white_check_mark: 4.14: Current CSV is: kubevirt-hyperconverged-operator.v4.14.6. Current operator version is: 4.14.6

:white_check_mark: 4.15: Current CSV is: kubevirt-hyperconverged-operator.v4.15.2. Current operator version is: 4.15.2

:warning: 4.16: Current CSV is: kubevirt-hyperconverged-operator.v4.14.0. Current operator version is: 4.14.0 (before this change, it was also installing this, so I think it is safe. And once 4.16 is released, it should automatically use a 4.16 version)

**Comment by mateusoliveira43** [comment]
/override ci/prow/4.14-e2e-test-aws
restore succeeds, but application not working flake (and PR does not touch that code)

**Review by weshayutin — APPROVED** [review]
/LGTM

**Pull request merged**
