### PR TITLE
OADP-1057: CloudStorageLocation Prefix/CACert support

### PR DESCRIPTION
**Pull request by kaovilai**
Related to https://github.com/openshift/openshift-velero-plugin/pull/199

In order to avoid conflict with velero expected folders, new validations has been added.

Change Summary
- bl.CloudStorage now support Prefix/CACert fields
- New validation errors when Prefix is not specified and backupImages is not false.
  ```
  BackupLocation must have velero prefix when backupImages is not set to false
  ```
  ```
  BackupLocation must have cloud storage prefix when backupImages is not set to false
  ```
- Convert BSL/VSL validation reconciler into a function called from ValidateDataProtectionCR function

#### Testing instructions
Prerequisites:
- https://mobb.ninja/docs/misc/oadp/rosa-sts/

Substitute operator install steps in prerequiste for the following operator-sdk run command.

To try this patch, get [operator-sdk](https://sdk.operatorframework.io/docs/installation/) and run
```bash
export OADP_TEST_NS=openshift-adp
(oc create namespace $OADP_TEST_NS || true) && \
operator-sdk run bundle ghcr.io/kaovilai/oadp-operator:csl-prefix-bundle --namespace $OADP_TEST_NS
```

cleanup
```
operator-sdk cleanup oadp-operator --namespace $OADP_TEST_NS
```
After cleanup, you will have to create dpa again.

### Example DPA
```yaml
cat << EOF | oc create -f -
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: ${CLUSTER_NAME}-dpa
  namespace: openshift-adp
spec:
  features:
    dataMover:
      enable: false
  backupLocations:
  - bucket:
      cloudStorageRef:
        name: ${CLUSTER_NAME}-oadp
      credential:
        key: credentials
        name: cloud-credentials
      default: true
      prefix: velero # added capability in oadp-operator#1126 PR
      config:
        region: ${REGION}
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
    restic:
      enable: false
  unsupportedOverrides:
    openshiftPluginImageFqin: ghcr.io/kaovilai/openshift-velero-plugin:sts
EOF
```

#### dev notes
bundle build command
```bash
IMG=ghcr.io/kaovilai/oadp-operator:csl-prefix-support-operator BUNDLE_IMG=ghcr.io/kaovilai/oadp-operator:csl-prefix-bundle make docker-build docker-push bundle bundle-build bundle-push
```

### CODE REVIEW

**Comment by kaovilai** [comment]
validated working :D

**Comment by kaovilai** [comment]
/hold
for https://github.com/openshift/openshift-velero-plugin/pull/199 to merge first

**Review by sseago — APPROVED** [review]

**Pull request merged**
