### PR TITLE
OADP-1.2 Cherry-pick of OADP-659: Remove HTTP/HTTPS port numbers from AWS S3 URLs. 

### PR DESCRIPTION
**Pull request by mrnold**
Cherry pick pull requests 1169 and 1177 for OADP 1.2.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/hold
wait 1.2.2 release

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
```
Pod todolist-1-cvcg4 not yet succeededstatus: {Pending [{Initialized False 0001-01-01 00:00:00 +0000 UTC 2023-10-12 18:41:14 +0000 UTC ContainersNotInitialized containers with incomplete status: [init-myservice]} {Ready False 0001-01-01 00:00:00 +0000 UTC 2023-10-12 18:41:14 +0000 UTC ContainersNotReady containers with unready status: [todolist]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2023-10-12 18:41:14 +0000 UTC ContainersNotReady containers with unready status: [todolist]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2023-10-12 18:41:14 +0000 UTC  }]    10.0.128.5 10.128.2.37 [{10.128.2.37}] 2023-10-12 18:41:14 +0000 UTC [{init-myservice {nil &ContainerStateRunning{StartedAt:2023-10-12 18:41:15 +0000 UTC,} nil} {nil nil nil} false 0 registry.access.redhat.com/ubi8/ubi:latest registry.access.redhat.com/ubi8/ubi@sha256:db870970ba330193164dacc88657df261d75bce1552ea474dbc7cf08b2fae2ed cri-o://7d3e1924e4f680d8d1435932ee67538ffaf70c5878bbb527e4ed88bdd19c862c <nil>}] [{todolist {&ContainerStateWaiting{Reason:PodInitializing,Message:,} nil nil} {nil nil nil} false 0 image-registry.openshift-image-registry.svc:5000/mongo-persistent/todolist-mongo-go@sha256:55a412a997c2144917c1e92a53b76977e794aee3c3f04fe0c8202ba8143640b9   0xc0010c3d68}] BestEffort []}
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oadp-operator/1180/pull-ci-openshift-oadp-operator-oadp-1.2-4.12-operator-e2e-azure/1712518428683669504#1:build-log.txt%3A1180
https://github.com/mrnold/oadp-operator/blob/a4bb58eab36119ccfcf3a2faeca7231ebcf7f326/tests/e2e/backup_restore_suite_test.go#L350
/retest

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
1.2.3 released
/unhold

**Pull request merged**
