### PR TITLE
[oadp-1.4] Fix OADP-3960: Split labels avoiding label key exceed allowed 63 chars

### PR DESCRIPTION
**Pull request by mateusoliveira43**
This is a cherry-pick of https://github.com/openshift/oadp-operator/pull/1392

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Comment by mateusoliveira43** [comment]
/unhold
we can start working on 1.4.1

**Comment by mateusoliveira43** [comment]
/override ci/prow/4.16-e2e-test-kubevirt-aws
Timeout was hit, it is addressed in another PR
```
2024/07/12 19:04:49 VM mysql-persistent/fedora-todolist status is: Terminating
  [FAILED] Expected
      <wait.errInterrupted>: 
      timed out waiting for the condition
```

**Pull request merged**
