### PR TITLE
CI: Enable upstream virtualization operator E2E tests.

### PR DESCRIPTION
**Pull request by mrnold**
## Why the changes were made

An early test of OpenShift 4.18 did not have the virtualization operator available in the usual place yet. This pull request enables testing with the upstream community KubeVirt operator with a new HCO_UPSTREAM test option.

## How to test the changes made

make TEST_VIRT=true HCO_UPSTREAM=true test-e2e

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]
Changes look sane. Thank you!

**Review by kaovilai — DISMISSED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by kaovilai** [comment]
4.17 is failing again..

**Comment by mrnold** [comment]
I finally managed to catch this live, looks like a problem with cloning the VM disk.

> VOLUME_MODE=filesystem
MOUNT_POINT=/var/run/cdi/clone/source
/var/run/cdi/clone/source /
Not preallocating filesystem, uploading only used bytes
UPLOAD_BYTES=22298624
I1018 21:21:51.166969 10 clone-source.go:224] content-type is "filesystem-clone"
I1018 21:21:51.167039 10 clone-source.go:225] mount is "/var/run/cdi/clone/source"
I1018 21:21:51.167043 10 clone-source.go:226] upload-bytes is 22298624
I1018 21:21:51.167051 10 clone-source.go:243] Starting cloner target
I1018 21:21:51.167092 10 clone-source.go:179] Executing /usr/bin/tar [cv -S disk.img]
I1018 21:21:51.565041 10 clone-source.go:259] Set header to filesystem-clone
F1018 21:21:51.599855 10 clone-source.go:120] Error io: read/write on closed pipe piping to gzip


> I1018 21:21:51.572454 1 uploadserver.go:438] Content type header is "filesystem-clone"
I1018 21:21:51.574228 1 file.go:264] copyWithSparseCheck to /dev/cdi-block-volume
E1018 21:21:51.574515 1 file.go:282] Error zeroing range in destination file: operation not supported
E1018 21:21:51.599561 1 uploadserver.go:452] Saving stream failed: operation not supported

I will check how this is supposed to work normally.

**Comment by mrnold** [comment]
/override 4.17-e2e-test-kubevirt-aws

This is fixed upstream: https://github.com/kubevirt/containerized-data-importer/pull/3434

I think it should be okay to override until the fix makes its way downstream.

**Comment by kaovilai** [comment]
4.18 is safe to ignore for now due to #1555

**Review by kaovilai — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
/lgtm

**Pull request merged**
