### PR TITLE
Handling Azure Parameters in CI Env using templates.

### PR DESCRIPTION
**Pull request by deepakraj1997**
- Moved most of the parameters to templates and scripts
- Removed redundant code and unused functions.

### CODE REVIEW

**Comment by mperetzred** [comment]
lgtm, great work @deepakraj1997 !

**Review by mperetzred — APPROVED** [review]

**Comment by kaovilai** [comment]
looks like I made a conflicting PR https://github.com/openshift/oadp-operator/pull/651 heh

**Comment by kaovilai** [comment]
If this can merge I'll merge this first.

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
