### PR TITLE
OADP-3165: Update default restore resource priorities

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**

### CODE REVIEW

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
Update default in documentation (I think is here https://github.com/openshift/oadp-operator/blob/master/pkg/velero/server/config.go#L41) and can you also add an example on how to reproduce the error of the issue so we can test it out?

**Comment by shubham-pampattiwar** [comment]
@mateusoliveira43 Slack thread confirming the change from the RFE reporter and tester: https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1705593931640569?thread_ts=1701439906.337739&cid=C0144ECKUJ0

**Comment by shubham-pampattiwar** [comment]
> right @shubham-pampattiwar , thanks
> 
> just missing the documentation update in DPA field now

Done, updated the PR ! PTAL !

**Review by mateusoliveira43 — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
