### PR TITLE
Updating velero dep after rebase 16 Oct 2023

### PR DESCRIPTION
**Pull request by sseago**
This also updated the x/net dep to 0.17.0

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]
Corresponds to velero force push
> build velero-helper binary for datamover pod
Force push
[sseago](https://github.com/sseago)force pushed to [konveyor-dev](https://github.com/openshift/velero/activity?ref=konveyor-dev) • b470b02…29f3739 • 1 hour ago

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]

**Comment by kaovilai** [comment]
fyi splitting out xnet update via dependabot to https://github.com/openshift/oadp-operator/pull/1194

**Comment by sseago** [comment]
@kaovilai splitting it out just means we have twice as many flaky CI tests to pass, especially since the velero update in this PR automatically pulled in the x/net bump due to the velero requirement for 0.17.0

**Pull request merged**
