### PR TITLE
Add DPA to `oc get all`

### PR DESCRIPTION
**Pull request by kaovilai**
Thoughts?

### CODE REVIEW

**Comment by shawn-hurley** [comment]
I would rather have backups and/or schedules in all but IDK especially for most ns's this is just going to be empty.

**Comment by kaovilai** [comment]
Right. But if you are debugging and your context is in the namespace where DPA is created, it will show.

**Comment by kaovilai** [comment]
> for most ns's this is just going to be empty.
Doesn't affect people day to day usage of their own namespace which is a good thing right? allows you to query all DPA when in the context of OADP namespace.

**Comment by shawn-hurley** [comment]
Pretty sure you adding a list call, for something that is always empty. I just don't know if from a wider perspective this would make us good citizens because we know those namespaced list calls will mostly be empty. Just my two cents

**Comment by kaovilai** [comment]
> adding a list call

I'm going to have to read more what this means.

Sounds like this would add burden to oc get outside the namespace context as well.

**Pull request closed without merging**
