### PR TITLE
Coverage/Go Report/License/Go Reference/Periodic Build badges, gitignore cover.out, codecov coverage upload

### PR DESCRIPTION
**Pull request by kaovilai**
- gitignore cover.out
- README.md
  - Go Report
  - Coverage (codecov)
  - License
  - Go Reference
  - Periodic Build badges
- Makefile codecov coverage upload
- codecov.yml token

README.md new header preview
---

> # OADP Operator
> [Go Report Card](https://goreportcard.com/report/github.com/openshift/oadp-operator) [codecov](https://codecov.io/gh/openshift/oadp-operator) [License](https://www.apache.org/licenses/LICENSE-2.0.html) [Go Reference](https://pkg.go.dev/github.com/openshift/oadp-operator)
> 
> AWS: [AWS builds](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-oadp-operator-master-operator-e2e-aws-periodic-slack)
> GCP: [GCP builds](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-oadp-operator-master-operator-e2e-gcp-periodic-slack)
> Azure: [Azure builds](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-oadp-operator-master-operator-e2e-azure-periodic-slack)

### CODE REVIEW

**Comment by kaovilai** [comment]
image

**Comment by kaovilai** [comment]
Try to implement codecov

**Comment by kaovilai** [comment]
Now using codecov
image

https://github.com/kaovilai/oadp-operator/tree/coverbadge_kaovilai_test

**Comment by kaovilai** [comment]
The codecov badge will update when you run `test_submitcoverage` against a git repo with sha already in master.
Therefore, it should update when postsubmit CI runs, or failing that, someone running it manually.

**Review by dymurray — APPROVED** [review]

**Pull request merged**
