### PR TITLE
Add Build-root dependency

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Review by dymurray — APPROVED** [review]

**Comment by alaypatel07** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oadp-operator/172/pull-ci-openshift-oadp-operator-master-ci-index/1425201947228508160#1:build-log.txt%3A9 build root seems to succeed here, failing on other step

/override all

**Pull request merged**
