### PR TITLE
CI: upload CirrOS disk image to DataVolume.

### PR DESCRIPTION
**Pull request by mrnold**
This pull request creates a small DataVolume and fills it with the CirrOS disk image so that later virtual machine tests can copy it locally.

### CODE REVIEW

**Comment by weshayutin** [comment]
qq why are the new virt asserts skipped?
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_oadp-operator/1315/pull-ci-openshift-oadp-operator-master-4.12-e2e-test-aws/1754627499213459456/artifacts/e2e-test-aws/e2e/build-log.txt
```
S [SKIPPED] [0.012 seconds]
VM backup and restore tests [BeforeAll]
/go/src/github.com/openshift/oadp-operator/tests/e2e/virt_backup_restore_suite_test.go:17
  should verify virt installation
  /go/src/github.com/openshift/oadp-operator/tests/e2e/virt_backup_restore_suite_test.go:50
------------------------------
S [SKIPPED] [0.000 seconds]
VM backup and restore tests
/go/src/github.com/openshift/oadp-operator/tests/e2e/virt_backup_restore_suite_test.go:12
  [It] should upload a data volume successfully
  /go/src/github.com/openshift/oadp-operator/tests/e2e/virt_backup_restore_suite_test.go:55
```

**Comment by mrnold** [comment]
> qq why are the new virt asserts skipped? https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_oadp-operator/1315/pull-ci-openshift-oadp-operator-master-4.12-e2e-test-aws/1754627499213459456/artifacts/e2e-test-aws/e2e/build-log.txt
> 

We are skipping them on 4.12 for now, because it needs extra work to replicate a new API field that was added in 4.13. https://github.com/openshift/oadp-operator/pull/1257#pullrequestreview-1798311014

**Comment by weshayutin** [comment]
ah... I see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_oadp-operator/1315/pull-ci-openshift-oadp-operator-master-4.14-e2e-test-aws/1754627499494477824/artifacts/e2e-test-aws/e2e/build-log.txt

Thanks @mrnold

**Review by kaovilai — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]

**Comment by kaovilai** [comment]
/override ci/prow/4.14-e2e-test-aws


```
  [FAILED] Expected
      <[]string | len:2, cap:2>: [
          "time=\"2024-02-06T16:24:21Z\" level=warning msg=\"VolumeSnapshot has a temporary error Failed to check and update snapshot content: failed to remove VolumeSnapshotBeingCreated annotation on the content snapcontent-73bd94ee-7866-433b-938d-7caf4787b299: \\\"snapshot controller failed to update snapcontent-73bd94ee-7866-433b-938d-7caf4787b299 on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \\\\\\\"snapcontent-73bd94ee-7866-433b-938d-7caf4787b299\\\\\\\": the object has been modified; please apply your changes to the latest version and try again\\\". Snapshot controller will retry later.\" backup=openshift-adp/mysql-twovol-csi-e2e-f719373f-c50b-11ee-b634-0a580a831c3c cmd=/plugins/velero-plugin-for-csi logSource=\"/opt/app-root/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:250\" pluginName=velero-plugin-for-csi",
          "time=\"2024-02-06T16:24:21Z\" level=error msg=0 backup=openshift-adp/mysql-twovol-csi-e2e-f719373f-c50b-11ee-b634-0a580a831c3c logSource=\"pkg/controller/backup_controller.go:729\"",
      ]
  to equal
      <[]string | len:0, cap:0>: []
  In [It] at: /go/src/github.com/openshift/oadp-operator/tests/e2e/backup_restore_suite_test.go:164 @ 02/06/24 16:37:32.793
```

**Comment by kaovilai** [comment]
Cherry pick?

**Comment by mrnold** [comment]
> Cherry pick?

I think this is going to stay on master for now.

**Pull request merged**
