### PR TITLE
[OADP-1.4] Bump up CirrOS image size for PSI

### PR DESCRIPTION
**Pull request by weshayutin**
Why the changes were made
Importing the CirrOS image into a cluster on OpenStack (storage class ocs-storagecluster-ceph-rbd-virtualization) fails with Virtual image size 117440512 is larger than the reported available storage 117317632. A larger PVC is required.

I'm not sure why this is the case, but bumping it up from 128M to 150 works.

How to test the changes made
E2E tests are not set up to run against OpenStack just yet, but hacking it up to do nothing but download the CirrOS image reproduces the bug and the fix. You can also create the Data Volume manually:

---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros
  namespace: openshift-virtualization-os-images
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 150Mi
  source:
    http:
      url: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
```

### CODE REVIEW

**Comment by weshayutin** [comment]
@mrnold FYI

**Review by mrnold — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by mrnold** [comment]
Oh right, the immediate-mode tests were already merged into 1.4. So the size change also needs to go into tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test-immediate.yaml

**Comment by mrnold** [comment]
Can you pull this in? https://github.com/weshayutin/oadp-operator/pull/19

**Comment by mateusoliveira43** [comment]
/hold
PR needs changes @mrnold pointed out

**Pull request closed without merging**
