### PR TITLE
fix: Delete unused files in E2E folder

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Delete unused files in E2E folder per https://github.com/openshift/oadp-operator/pull/1283#issuecomment-2009954563.

## How to test the changes made

Check that deleted files are really not used or mentioned, by checking CI and running commands like `grep`.

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
