### PR TITLE
OADP-1927: Fix VSL secret validation

### PR DESCRIPTION
**Pull request by PrasadJoshi12**

### CODE REVIEW

**Comment by weshayutin** [comment]
@PrasadJoshi12 thank you very much and well done, taking a look

**Comment by PrasadJoshi12** [comment]
Thank you @weshayutin and @kaovilai

**Comment by kaovilai** [comment]
note that cherry-picks here is for 1.2.1, hold it till 1.2.0 is released.

**Review by eemcmullan — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
