### PR TITLE
OADP Operator update for aug-22-2024 velero rebase

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
## Why the changes were made

Go mod and CRD updates required due to Velero rebase 

## How to test the changes made

Any kind of E2E sanity testing would be helpful here !

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by sseago — APPROVED** [review]

**Review by kaovilai — DISMISSED** [review]
/lgtm

**Comment by mateusoliveira43** [comment]
I think this needs to be updated https://github.com/openshift/oadp-operator/blob/master/tests/e2e/virt_backup_restore_suite_test.go#L245

after rebase, should not error anymore, right?

**Comment by kaovilai** [comment]
unless there's merge conflict, rebasing should not be necessary. retest should test against new base ref merged with pr.

**Comment by kaovilai** [comment]
> I think this needs to be updated https://github.com/openshift/oadp-operator/blob/master/tests/e2e/virt_backup_restore_suite_test.go#L245

ya agree. seems to be successful now.. if expected, need to remove this RestoreErr

**Review by mateusoliveira43 — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]
/LGTM

**Pull request merged**
