### PR TITLE
Make vsm relatedImage name consistent

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]
/lgtm

**Comment by weshayutin** [comment]
@shubham-pampattiwar thank you!

**Comment by rayfordj** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oadp-operator/765/pull-ci-openshift-oadp-operator-master-4.10-operator-e2e-gcp/1549734157016371200

```
{  could not create build test-oadp-operator: 
Build.build.openshift.io "test-oadp-operator" is invalid:
spec.output.imageLabels[9].name: 
Invalid value: "io.openshift.ci.from.ocp_builder_rhel-8-golang-1.16-openshift-4.9": 
name part must be no more than 63 characters}
```

**Pull request merged**
