### PR TITLE
Remove VSB and VSR from OADP 1.3+

### PR DESCRIPTION
**Pull request by mpryc**
Since VSB and VSR is not needed in OADP 1.3+ removing it from the CSV.

Updated API_ref and script to not show errors. E.g. when the ocp is missing those APIs, however left the functions in the datamover_resources.sh as one may want to run it against earlier OADP versions.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
fixes https://github.com/openshift/oadp-operator/issues/1211

**Review by mateusoliveira43 — APPROVED** [review]

**Comment by shubham-pampattiwar** [comment]
Shouldn't we also remove it from bundle/manifests ?

**Comment by shubham-pampattiwar** [comment]
if that's already done or you want to do it in a follow up PR, feel free to merge this existing PR.

**Comment by mateusoliveira43** [comment]
@shubham-pampattiwar thats already done, otherwise unit test would have failed

I think because that CRD does not exist in master, it does not go to bundle even running `make bundle`

**Comment by shubham-pampattiwar** [comment]
Thanks @mate usoliveira43

**Pull request merged**
