### PR TITLE
oadp-1.0: OADP-389 `go get github.com/prometheus/client_golang@v1.11.1`

### PR DESCRIPTION
**Pull request by kaovilai**

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]
/lgtm

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
letting all 3 fail first then retesting after https://github.com/openshift/oadp-operator/pull/832

**Comment by kaovilai** [comment]
or I guess I can start a new test now..
/test ci/prow/4.7-operator-e2e 
/test ci/prow/4.8-operator-e2e 
/test  ci/prow/4.9-operator-e2e

**Pull request merged**
