### PR TITLE
OADP-382: Introduce stable-1.1 channel

### PR DESCRIPTION
**Pull request by rayfordj**

### CODE REVIEW

**Comment by kaovilai** [comment]
Please merge https://github.com/rayfordj/oadp-operator/pull/1 and we're good.

**Comment by rayfordj** [comment]
> Please merge [rayfordj#1](https://github.com/rayfordj/oadp-operator/pull/1) and we're good.

Thanks, @kaovilai!

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
