### PR TITLE
Implementation function for unsupported args. (#1423)

### PR DESCRIPTION
**Pull request by mpryc**
## Why the changes were made

This is an cherry-pick of https://github.com/openshift/oadp-operator/pull/1423

### CODE REVIEW

**Comment by mpryc** [comment]
I think we need to cherry-pick https://github.com/openshift/oadp-operator/pull/1397 first, so it's clean path

**Comment by kaovilai** [comment]
unit test failed
```
vet: pkg/common/common_test.go:156:18: undefined: corev1

```

**Comment by mpryc** [comment]
Closing, new automated cherry-pick without need to manually modify the code-base available at: https://github.com/openshift/oadp-operator/pull/1462

**Pull request closed without merging**
