### PR TITLE
OADP 486 - Update velero service account permissions

### PR DESCRIPTION
**Pull request by dymurray**

### CODE REVIEW

**Comment by kaovilai** [comment]
If we are removing velero-privileged here maybe remove the SCC from reconciler in go too?

**Comment by dymurray** [comment]
I didn't even realize we were still creating that SCC. I don't want to introduce too much churn into 1.0.3.... I will keep that for now
open a separate issue to remove the SCC bits

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
