### PR TITLE
awk for azure resource group can accept unformatted json

### LINKED ISSUE #658: Bug: Azure E2E using `-rg` resource group
### Contact Details

_No response_

### Describe bug

If content of
https://github.com/openshift/oadp-operator/blob/69ce063c2bb4b8eaba10d15cdb570ec70c7a8dbc/Makefile#L26
is believed to be
https://github.com/openshift/oadp-operator/blob/b3ca1c3844c5a66d012bc47d01918226c2d3ead9/docs/developer/testing/%20MULTI_CLOUD_TESTING_UPDATES.md#L71-L74
then
https://github.com/openshift/oadp-operator/blob/69ce063c2bb4b8eaba10d15cdb570ec70c7a8dbc/tests/e2e/scripts/azure_settings.sh#L7
is not getting infraID correctly.
The output of
```
echo '{"clusterName":"ci-op-w718n0np-32d40","clusterID":"6de2d426-68af-43d3-9d1a-d72666edc550","infraID":"ci-op-w718n0np-32d40-4fdtv","azure":{"cloudName":"AzurePublicCloud","region":"eastus","resourceGroupName":""}}' | awk '/infraID/ { gsub(/["]|,.*/,""); print $2}'
```
is in fact
```sh
#empty
```

### What happened?
Resource group `-rg` was (occasionally?) used
https://github.com/openshift/oadp-operator/blob/69ce063c2bb4b8eaba10d15cdb570ec70c7a8dbc/tests/e2e/scripts/azure_settings.sh#L10
and causes Azure CI run to fail
```
time="2022-04-30T03:54:36Z" level=error msg="Error backing up item" backup=openshift-adp/mysql-e2e-0cd8e63e-c839-11ec-88cf-0a580a81136e error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceGroupNotFound\" Message=\"Resource group '-rg' could not be found.\"" logSource="pkg/backup/backup.go:417" name=mysql-6bb6964964-kbwxj

```
https://github.com/openshift/oadp-operator/pull/654#issuecomment-1113924553

### OADP Version

Unreleased (built from source)

### OpenShift Version

_No response_

### Velero pod logs

_No response_

### Restic pod logs

_No response_

### Operator pod logs

_No response_

### New issue

- [X] This issue is new

### PR DESCRIPTION
**Pull request by kaovilai**
Fix #658
Make awk regex used for azure resource group work when input json is an unformatted single line.

### CODE REVIEW

**Comment by kaovilai** [comment]
Closed in favor of #654 if

**Comment by kaovilai** [comment]
oops didn't see lgtm. :D

**Comment by kaovilai** [comment]
> maybe formatting issue ? 
I think it depends which config files you end up getting which may differ from region/cluster/zones that are outside our control. But sounds like majority of the cluster had unformatted, no newline, json.

**Comment by deepakraj1997** [comment]
Got it. Please close this PR when you see fit since you have already included these in the #654, you might have a clash or need to do a rebase if both goes in.

**Pull request closed without merging**
