### PR TITLE
fix: dc post restore script logic to delete disconnected pods

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Add `--all-namespaces` flag to delete command. This should make CI more stable.

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by mpryc** [comment]
> We changed the name of the script, but not the prow config... can someone trigger e2e run for me in this PR?

There is symlink to the old one to ensure it's compatible, because it's mentioned in many places in docs even outside of OADP repo.

**Pull request merged**
