### PR TITLE
[oadp-1.4] OADP-4379: read ephemeral-storage in code

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

cherry picked from commit https://github.com/openshift/oadp-operator/commit/b51ce21d3df79005a81ed6e579a3359cffa46b0f : PR https://github.com/openshift/oadp-operator/pull/1477

## How to test the changes made

Follow instructions from parent PR.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/retest
infra and post restore flake

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]
/LGTM

**Comment by weshayutin** [comment]
hrm... this doesn't seem like a "flake" more like build / containers aren't right, but unrelated to this patch.

**Pull request merged**
