### PR TITLE
[oadp-1.3] Fix OADP-3228: Controller Manager lease duration too short for SNO (#1264)

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
* Update controller manager lease based on cluster topology

* Update operator code to be independent of openshift library

* minor fixes

* remove duplicate rest config call

(cherry picked from commit c49ab62cda88c8d7cb2c29db51e871e1610e74a6)

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Review by mateusoliveira43 — APPROVED** [review]
/lgtm

**Comment by kaovilai** [comment]
will lgtm after https://github.com/openshift/oadp-operator/pull/1340

**Pull request merged**
