### PR TITLE
fix: Update NAC CRDs

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Update NAB CRD for https://github.com/migtools/oadp-non-admin/pull/114

## How to test the changes made

Follow NAC development documentation.

### CODE REVIEW

**Review by mpryc — APPROVED** [review]
Checked by:

```shell
$ gh pr checkout 1599
$ export /path/to/non-admin/repo/with/pr/114
$ make update-non-admin-manifests
```

There were 0 changes in the diff.

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
