### PR TITLE
Running must gather after each tests

### PR DESCRIPTION
**Pull request by deepakraj1997**
- Was trying to run using oc client, but after some research, it may very cumbersome to run `oc adm ...` commands using oc go client.
- Running must gather using shell.

### CODE REVIEW

**Comment by weshayutin** [comment]
woot... thank you @deepakraj1997 for looking into this!

**Comment by hhpatel14** [comment]
https://coreos.slack.com/archives/CFUGK0K9R/p1647955342187699 We are running our tests on build03.

**Comment by deepakraj1997** [comment]
Pending: To updated using 'oc' from CLI_DIR

**Comment by weshayutin** [comment]
NICE! @hhpatel14  FYI

**Pull request merged**
