### PR TITLE
Manifest updates for the NonAdminBackup PR 108

### PR DESCRIPTION
**Pull request by mpryc**
Updates to the manifests required by the NAB PR:
  https://github.com/migtools/oadp-non-admin/pull/108

## Why the changes were made

To allow PR   https://github.com/migtools/oadp-non-admin/pull/108 to be merged

## How to test the changes made

Auto-generated by running `make update-non-admin-manifests`

### CODE REVIEW

**Review by shubham-pampattiwar — CHANGES_REQUESTED** [review]
Please also add the relevant permissions needed to the NAC SA via OADP CSV for facilitating NAB Delete feature.

**Review by mateusoliveira43 — APPROVED** [review]

**Pull request merged**
