### PR TITLE
velero main rebase to topic branch, 7 Aug 2023

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by mpryc — COMMENTED** [review]
May I ask how this is being synced / what is the process ? Is the rebase some manual copy paste?

My understanding is that those bases files are same as:
https://github.com/vmware-tanzu/velero/blob/81057b9983ea8798ce410a8dd52dce99c5023c85/config/crd/v1/bases/velero.io_restores.yaml

There is also fork of the upstream velero at https://github.com/openshift/velero

So my understanding is that:

Upstream vmware-tanzu/velero Velero ---> Rebased openshift/velero repo from vmware-tanzu/velero ---> OADP operator repo /copied versions of crd/bases from Rebased openshift velero/ ---> generate manifests/bundle in the OADP Operator.

If the above is true, I'd like here info where the rebased  openshift/velero change is or at least some link on when that happened in the git history.

Unless there is a better way e.g. lines:
```
github.com/openshift/velero v0.10.2-0.20230807193253-f0d1b0495a09 h1:UQF6Srm4+lV3Nm3w6Fs9Sto5Ff7yKE7qMRAhztrqrPA=
github.com/openshift/velero v0.10.2-0.20230807193253-f0d1b0495a09/go.mod h1:nf1mFikxiN+rhWqpXe38Ut4xyh5ETqdbtk8Byh3+hDg=
```

**Comment by sseago** [comment]
@mpryc So yes, we rebased the konveyor-dev branch of velero to upstream main. This PR does 2 thing:
1) copies CRDs from that branch into oadp-operator and runs `make bundle`
2) `go mod edit -replace github.com/vmware-tanzu/velero=github.com/openshift/velero@konveyor-dev; go mod tidy`

**Review by kaovilai — APPROVED** [review]
/lgtm

**Pull request merged**
