### PR TITLE
Fix OADP-3232: Controller Manager lease duration too short for SNO (#…

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
…1264)

* Update controller manager lease based on cluster topology

* Update operator code to be independent of openshift library

* minor fixes

* remove duplicate rest config call

(cherry picked from commit c49ab62cda88c8d7cb2c29db51e871e1610e74a6)

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by shubham-pampattiwar** [comment]
Closing this PR as no longer needed on OADP 1.2.x release.
Fix already merged on OADP 1.3 and master.

**Pull request closed without merging**
