### PR TITLE
OADP-3562: Fix controller panic on secret key-value parsing

### PR DESCRIPTION
**Pull request by stillalearner**
Fixes -> https://issues.redhat.com/browse/OADP-3562 

Tested successfully with empty value for key.

status:
  conditions:
  - lastTransitionTime: "2024-09-24T09:04:15Z"
    message: secret parsing error in key AZURE_STORAGE_ACCOUNT_ACCESS_KEY
    reason: Error
    status: "False"
    type: Reconciled

### CODE REVIEW

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
Thanks @stillalearner !

But lets ensure we never make this mistake again. Please add `loggercheck` to `.golangci.yaml`, as described
https://github.com/openshift/oadp-operator/blob/94bc5ae81e15c97b605ce416421782a12b672327/.golangci.yaml#L96-L97
```diff
   # - ineffassign
+  - loggercheck
   # - misspell
```

Running linters on master with this change, the error is caught  
```console
$ make lint
PATH/bin/golangci-lint run
controllers/registry.go:475:47: odd number of arguments passed as key-value pairs for logging (loggercheck)
		r.Log.Info("Could not parse secret for %s", key)
		                                            ^
make: *** [Makefile:553: lint] Error 1
```

**Review by mateusoliveira43 — APPROVED** [review]
For next PRs, do not forget to use [the project's PR template](https://github.com/openshift/oadp-operator/blob/master/.github/pull_request_template.md?plain=1) for the PR's description

Some examples of using it
- https://github.com/openshift/oadp-operator/pull/1478#issue-2432232373
- https://github.com/openshift/oadp-operator/pull/1492#issue-2465925347
- https://github.com/openshift/oadp-operator/pull/1477#issue-2430630778

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Comment by mateusoliveira43** [comment]
/unhold
E2E tests are working again

**Pull request merged**
