### PR TITLE
[oadp-1.4] OADP-5072: Default permission for Secrets

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

cherry picked from commit https://github.com/openshift/oadp-operator/commit/1a17d7c08b30e1cae9e3a11e952d53b02afdadbf : PR https://github.com/openshift/oadp-operator/pull/1539

## How to test the changes made

Follow instructions from parent PR.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Comment by kaovilai** [comment]
ehh.. this 4.18 job was optional.. why is it not optional now..
/override ci/prow/4.18-dev-preview-e2e-test-aws

**Comment by kaovilai** [comment]
still optional [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.18-dev-preview.yaml#L35).. asking in test-platform

**Comment by kaovilai** [comment]
and optional [here](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml#L1205)

**Comment by kaovilai** [comment]
ahh 1.4

**Pull request merged**
