### PR TITLE
fix: restic removal message

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Change restic removal message. It wont be remove in OADP 1.4 anymore.

## How to test the changes made

Check that all necessary places where modified (I ran `grep -Iinr '1\.4' . --exclude=\*.{sum,mod,svg,out} --exclude-dir=developer` to help myself).

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — DISMISSED** [review]

**Comment by mateusoliveira43** [comment]
/hold
1.4 general hold

**Review by mpryc — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Review by mpryc — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
/override ci/prow/4.14-e2e-test-aws
restore succeeds, but application not working flake

**Pull request merged**
