### PR TITLE
Update openshift/velero references in go.mod

### PR DESCRIPTION
**Pull request by kaovilai**
To make  deploy-olm work in master
Bump openshift/velero to oadp-1.2 latest
remove `sigs.k8s.io/controller-runtime/pkg/envtest/printer` dependency
go fmt
bundle update.

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
WFM, does this put 1.2.0 at risk if we cherry pick over?

**Comment by kaovilai** [comment]
Don't think its a risk.. the only change is added generated field for resourceAllocations.. no deletions/updates to existing.

**Comment by weshayutin** [comment]
```
ysql]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2023-05-20 08:46:49 +0000 UTC ContainersNotReady containers with unready status: [mysql]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2023-05-20 08:46:49 +0000 UTC  }]    10.0.128.2  [] 2023-05-20 08:46:49 +0000 UTC [] [{mysql {&ContainerStateWaiting{Reason:ContainerCreating,Message:,} nil nil} {nil nil nil} false 0 registry.redhat.io/rhel8/mariadb-105:latest   0xc0010cedcf}] Burstable []}backup phase: InProgress
  backup phase: InProgress
  backup phase: InProgress
  backup phase: InProgress
  backup phase: WaitingForPluginOperations
  backup phase: WaitingForPluginOperations
  <snip>
  backup phase: WaitingForPluginOperations
  [38;5;9m[FAILED][0m in [It] - /go/src/github.com/openshift/oadp-operator/tests/e2e/backup_restore_suite_test.go:301 [38;5;243m@ 05/20/23 09:07:07.316[0m
  Report after each: state:  failed
  Printing app namespace events
  Event: Created pod: mysql-6bd8d944f8-flpb6, Type: Normal, Count: 1, Src: {ReplicaSet mysql-persistent mysql-6bd8d944f8 18b43e6b-a0e3-445c-b539-3ea3eeaffac1 apps/v1 65778 }, Reason: SuccessfulCreate
  Event: Created new replication controller "todolist-1" for version 1, Type: Normal, Count: 1, Src: {DeploymentConfig mysql-persistent todolist 25886e59-3eb4-430b-997d-0440249e81ac apps.openshift.io/v1 65796 }, Reason: DeploymentCreated
  Event: waiting for pod mysql-6bd8d944f8-flpb6 to be scheduled, Type: Normal, Count: 1, Src: {PersistentVolumeClaim mysql-persistent mysql b9d44385-d4ca-4f1f-89a1-a0b197c93f62 v1 65803 }, Reason: WaitForPodScheduled
  Event: Scaled up replica set mysql-6bd8d944f8 to 1, Type: Normal, Count: 1, Src: {Deployment mysql-persistent mysql 88860996-9436-469d-988d-9eb311f01ef8 apps/v1 65776 }, Reason: ScalingReplicaSet
  Event: Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:198af23445eed9dc258de659335a848aa7c3b43c750de25e505ca2726b60f751" already present on machine, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-deploy 6d69da3d-0aef-4d2a-9af7-2eca8e24eb44 v1 65811 spec.containers{deployment}}, Reason: Pulled
  Event: Add eth0 [10.128.2.34/23] from openshift-sdn, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-deploy 6d69da3d-0aef-4d2a-9af7-2eca8e24eb44 v1 65814 }, Reason: AddedInterface
  Event: External provisioner is provisioning volume for claim "mysql-persistent/mysql", Type: Normal, Count: 1, Src: {PersistentVolumeClaim mysql-persistent mysql b9d44385-d4ca-4f1f-89a1-a0b197c93f62 v1 65828 }, Reason: Provisioning
  Event: waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator, Type: Normal, Count: 1, Src: {PersistentVolumeClaim mysql-persistent mysql b9d44385-d4ca-4f1f-89a1-a0b197c93f62 v1 65828 }, Reason: ExternalProvisioning
  Event: Created container deployment, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-deploy 6d69da3d-0aef-4d2a-9af7-2eca8e24eb44 v1 65811 spec.containers{deployment}}, Reason: Created
  Event: Started container deployment, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-deploy 6d69da3d-0aef-4d2a-9af7-2eca8e24eb44 v1 65811 spec.containers{deployment}}, Reason: Started
  Event: Created pod: todolist-1-d7qzd, Type: Normal, Count: 1, Src: {ReplicationController mysql-persistent todolist-1 f46ee16a-58f6-456e-b537-369be861d632 v1 65864 }, Reason: SuccessfulCreate
  Event: Pulling image "registry.access.redhat.com/ubi8/ubi:latest", Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.initContainers{init-myservice}}, Reason: Pulling
  Event: Successfully provisioned volume pvc-b9d44385-d4ca-4f1f-89a1-a0b197c93f62, Type: Normal, Count: 1, Src: {PersistentVolumeClaim mysql-persistent mysql b9d44385-d4ca-4f1f-89a1-a0b197c93f62 v1 65828 }, Reason: ProvisioningSucceeded
  Event: Add eth0 [10.131.0.28/23] from openshift-sdn, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65872 }, Reason: AddedInterface
  Event: Successfully pulled image "registry.access.redhat.com/ubi8/ubi:latest" in 944.115193ms, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.initContainers{init-myservice}}, Reason: Pulled
  Event: Created container init-myservice, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.initContainers{init-myservice}}, Reason: Created
  Event: Started container init-myservice, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.initContainers{init-myservice}}, Reason: Started
  Event: AttachVolume.Attach succeeded for volume "pvc-b9d44385-d4ca-4f1f-89a1-a0b197c93f62" , Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65905 }, Reason: SuccessfulAttachVolume
  Event: Pulling image "quay.io/konveyor/todolist-mariadb-go:v2_4", Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.containers{todolist}}, Reason: Pulling
  Event: Add eth0 [10.129.2.41/23] from openshift-sdn, Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65907 }, Reason: AddedInterface
  Event: Pulling image "registry.redhat.io/rhel8/mariadb-105:latest", Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65905 spec.containers{mysql}}, Reason: Pulling
  Event: Successfully pulled image "registry.redhat.io/rhel8/mariadb-105:latest" in 1.028572753s, Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65905 spec.containers{mysql}}, Reason: Pulled
  Event: Started container mysql, Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65905 spec.containers{mysql}}, Reason: Started
  Event: Created container mysql, Type: Normal, Count: 1, Src: {Pod mysql-persistent mysql-6bd8d944f8-flpb6 b0ebc591-d58b-4049-b7f1-20fe83743a06 v1 65905 spec.containers{mysql}}, Reason: Created
  Event: Successfully pulled image "quay.io/konveyor/todolist-mariadb-go:v2_4" in 2.035757097s, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.containers{todolist}}, Reason: Pulled
  Event: Container image "quay.io/konveyor/todolist-mariadb-go:v2_4" already present on machine, Type: Normal, Count: 1, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.containers{todolist}}, Reason: Pulled
  Event: Started container todolist, Type: Normal, Count: 2, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.containers{todolist}}, Reason: Started
  Event: Created container todolist, Type: Normal, Count: 2, Src: {Pod mysql-persistent todolist-1-d7qzd b2486478-6e2a-4642-b7c5-90985e320558 v1 65868 spec.containers{todolist}}, Reason: Created
  Event: Waiting for a snapshot mysql-persistent/velero-mysql-v9gxv to be created by the CSI driver., Type: Normal, Count: 1, Src: {VolumeSnapshot mysql-persistent velero-mysql-v9gxv f7e7363b-b8a3-4c21-8b98-ed81a239bd2f snapshot.storage.k8s.io/v1 66110 }, Reason: CreatingSnapshot
  Event: Snapshot mysql-persistent/velero-mysql-v9gxv was successfully created by the CSI driver., Type: Normal, Count: 1, Src: {VolumeSnapshot mysql-persistent velero-mysql-v9gxv f7e7363b-b8a3-4c21-8b98-ed81a239bd2f snapshot.storage.k8s.io/v1 66118 }, Reason: SnapshotCreated
  Event: Snapshot mysql-persistent/velero-mysql-v9gxv is ready to use., Type: Normal, Count: 1, Src: {VolumeSnapshot mysql-persistent velero-mysql-v9gxv f7e7363b-b8a3-4c21-8b98-ed81a239bd2f snapshot.storage.k8s.io/v1 66149 }, Reason: SnapshotReady
  Printing oadp namespace events
  Event: Snapshot openshift-adp/snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot was successfully created by the CSI driver., Type: Normal, Count: 1, Src: {VolumeSnapshot openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot d5a6ef68-2403-47ab-a036-e73c3f25981f snapshot.storage.k8s.io/v1 66380 }, Reason: SnapshotCreated
  Event: Snapshot openshift-adp/snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot is ready to use., Type: Normal, Count: 1, Src: {VolumeSnapshot openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot d5a6ef68-2403-47ab-a036-e73c3f25981f snapshot.storage.k8s.io/v1 66380 }, Reason: SnapshotReady
  Event: performed created on volumesnapshot snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot, Type: Normal, Count: 1, Src: {VolumeSnapshot openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-clone-volumesnapshot d5a6ef68-2403-47ab-a036-e73c3f25981f snapshot.storage.k8s.io/v1 66380 }, Reason: VolumeSnapshotReconciled
  Event: created restic secret vsb-rxl9k-secret, Type: Normal, Count: 1, Src: {Secret openshift-adp vsb-rxl9k-secret fddc5e15-ce94-4bf0-9f4e-3ef7d99dfd76 v1 66429 }, Reason: ResticSecretBackupReconciled
  Event: performed created on PVC snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc, Type: Normal, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66425 }, Reason: PVCReconciled
  Event: waiting for first consumer to be created before binding, Type: Normal, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66425 }, Reason: WaitForFirstConsumer
  Event: performed created on pod vsb-rxl9k-pod, Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66428 }, Reason: PodReconciled
  Event: failed to provision volume with StorageClass "standard-csi": rpc error: code = DeadlineExceeded desc = context deadline exceeded, Type: Warning, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: ProvisioningFailed
  Event: failed to provision volume with StorageClass "standard-csi": rpc error: code = Aborted desc = An operation with the given Volume ID projects/XXXXXXXXXXXXXXXXXXXXXX/zones/us-central1-c/disks/pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5 already exists, Type: Warning, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: ProvisioningFailed
  Event: failed to provision volume with StorageClass "standard-csi": rpc error: code = Internal desc = CreateVolume existing disk Key{"pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5", zone: "us-central1-c"} is not ready, Type: Warning, Count: 2, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: ProvisioningFailed
  Event: waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator, Type: Normal, Count: 3, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: ExternalProvisioning
  Event: Successfully provisioned volume pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5, Type: Normal, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: ProvisioningSucceeded
  Event: External provisioner is provisioning volume for claim "openshift-adp/snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc", Type: Normal, Count: 5, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66433 }, Reason: Provisioning
  Event: created replicationsource vsb-rxl9k-rep-src, Type: Normal, Count: 1, Src: {ReplicationSource openshift-adp vsb-rxl9k-rep-src cbc3d235-c2d2-4600-ae48-337cc42fe2a5 volsync.backube/v1alpha1 66670 }, Reason: ReplicationSourceReconciled
  Event: waiting for first consumer to be created before binding, Type: Normal, Count: 1, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-rxl9k-rep-src-cache 0363bda4-5630-4278-9b45-8c7e153a262f v1 66675 }, Reason: WaitForFirstConsumer
  Event: created PersistentVolumeClaim/volsync-vsb-rxl9k-rep-src-cache to receive incoming data, Type: Normal, Count: 1, Src: {ReplicationSource openshift-adp vsb-rxl9k-rep-src cbc3d235-c2d2-4600-ae48-337cc42fe2a5 volsync.backube/v1alpha1 66671 }, Reason: PersistentVolumeClaimCreated
  Event: Created pod: volsync-src-vsb-rxl9k-rep-src-bwxj4, Type: Normal, Count: 1, Src: {Job openshift-adp volsync-src-vsb-rxl9k-rep-src 7c3da633-6ccc-4b83-92e0-78b7884b186c batch/v1 66681 }, Reason: SuccessfulCreate
  Event: AttachVolume.Attach succeeded for volume "pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5" , Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 }, Reason: SuccessfulAttachVolume
  Event: MountVolume.NodeExpandVolume failed for volume "pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5" requested read-only file system, Type: Warning, Count: 1, Src: {PersistentVolumeClaim openshift-adp snapcontent-f7e7363b-b8a3-4c21-8b98-ed81a239bd2f-pvc 8ba3134b-222d-4f62-b153-5f53ed4107b5 v1 66628 }, Reason: FileSystemResizeFailed
  Event: MountVolume.NodeExpandVolume failed for volume "pvc-8ba3134b-222d-4f62-b153-5f53ed4107b5" requested read-only file system, Type: Warning, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 }, Reason: FileSystemResizeFailed
  Event: Pulling image "quay.io/konveyor/rsync-transfer:latest", Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 spec.containers{busybox}}, Reason: Pulling
  Event: Add eth0 [10.128.2.35/23] from openshift-sdn, Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66634 }, Reason: AddedInterface
  Event: Started container busybox, Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 spec.containers{busybox}}, Reason: Started
  Event: Successfully pulled image "quay.io/konveyor/rsync-transfer:latest" in 579.961928ms, Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 spec.containers{busybox}}, Reason: Pulled
  Event: Created container busybox, Type: Normal, Count: 1, Src: {Pod openshift-adp vsb-rxl9k-pod 6ca50e8c-1a5a-42ba-b583-23f84537797e v1 66632 spec.containers{busybox}}, Reason: Created
  Event: failed to provision volume with StorageClass "standard-csi": rpc error: code = InvalidArgument desc = VolumeContentSource must be provided when AccessMode is set to read only, Type: Warning, Count: 15, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-2prln-rep-src-cache ce4eb923-f140-4d5c-9ba5-b83836374fad v1 58052 }, Reason: ProvisioningFailed
  Event: waiting for PersistentVolumeClaim/volsync-vsb-2prln-rep-src-cache to bind; check StorageClass name and CSI driver capabilities, Type: Warning, Count: 34, Src: {ReplicationSource openshift-adp vsb-2prln-rep-src 09a0cb40-66bf-4201-a149-5008b40cc363 volsync.backube/v1alpha1 58056 }, Reason: PersistentVolumeClaimNotBound
  Event: waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator, Type: Normal, Count: 145, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-2prln-rep-src-cache ce4eb923-f140-4d5c-9ba5-b83836374fad v1 58052 }, Reason: ExternalProvisioning
  Event: waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator, Type: Normal, Count: 63, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-rxl9k-rep-src-cache 0363bda4-5630-4278-9b45-8c7e153a262f v1 66689 }, Reason: ExternalProvisioning
  Event: performed updated on datamover deployment openshift-adp/volume-snapshot-mover, Type: Normal, Count: 93, Src: {Deployment openshift-adp volume-snapshot-mover 0f2e2a96-a7e9-4add-8da7-9e8db362b45c apps/v1 56078 }, Reason: DataMoverDeploymentReconciled
  Event: External provisioner is provisioning volume for claim "openshift-adp/volsync-vsb-2prln-rep-src-cache", Type: Normal, Count: 18, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-2prln-rep-src-cache ce4eb923-f140-4d5c-9ba5-b83836374fad v1 58052 }, Reason: Provisioning
  Event: waiting for PersistentVolumeClaim/volsync-vsb-rxl9k-rep-src-cache to bind; check StorageClass name and CSI driver capabilities, Type: Warning, Count: 17, Src: {ReplicationSource openshift-adp vsb-rxl9k-rep-src cbc3d235-c2d2-4600-ae48-337cc42fe2a5 volsync.backube/v1alpha1 66700 }, Reason: PersistentVolumeClaimNotBound
  Event: failed to provision volume with StorageClass "standard-csi": rpc error: code = InvalidArgument desc = VolumeContentSource must be provided when AccessMode is set to read only, Type: Warning, Count: 13, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-rxl9k-rep-src-cache 0363bda4-5630-4278-9b45-8c7e153a262f v1 66689 }, Reason: ProvisioningFailed
  Event: External provisioner is provisioning volume for claim "openshift-adp/volsync-vsb-rxl9k-rep-src-cache", Type: Normal, Count: 13, Src: {PersistentVolumeClaim openshift-adp volsync-vsb-rxl9k-rep-src-cache 0363bda4-5630-4278-9b45-8c7e153a262f v1 66689 }, Reason: Provisioning
  Printing volsync namespace events
```

**Comment by weshayutin** [comment]
@kaovilai ugh.. this is an issue in 1.2 as well afaict

```
[whayutin@thinkdoe oadp-operator]$ make deploy-olm 
$CLUSTER_TYPE is [aws]
# Download operator-sdk locally if does not exist
if [ ! -f /home/whayutin/OPENSHIFT/git/OADP/oadp-operator/bin/operator-sdk ]; then \
	mkdir -p bin ;\
	curl -Lo /home/whayutin/OPENSHIFT/git/OADP/oadp-operator/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v1.23.0/operator-sdk_linux_amd64 ; \
	chmod +x /home/whayutin/OPENSHIFT/git/OADP/oadp-operator/bin/operator-sdk; \
fi
oc whoami # Check if logged in
kube:admin
oc create namespace openshift-adp || true
namespace/openshift-adp created
/home/whayutin/OPENSHIFT/git/OADP/oadp-operator/bin/operator-sdk cleanup oadp-operator --namespace openshift-adp
WARN[0000] Cleanup operator: package "oadp-operator" not found 
DEPLOY_TMP: /tmp/tmp.SvlmU2Qpbn/ 
# build and push operator and bundle image
# use /home/whayutin/OPENSHIFT/git/OADP/oadp-operator/bin/operator-sdk to install bundle to authenticated cluster
cp -r . /tmp/tmp.SvlmU2Qpbn/  && cd /tmp/tmp.SvlmU2Qpbn/  && \
IMG=ttl.sh/oadp-operator-8a97b74:1h  BUNDLE_IMG=ttl.sh/oadp-operator-bundle-8a97b74:1h  \
	make docker-build docker-push bundle bundle-build bundle-push; \
rm -rf /tmp/tmp.SvlmU2Qpbn/ 
make[1]: Entering directory '/tmp/tmp.SvlmU2Qpbn'
$CLUSTER_TYPE is [aws]
# Commenting out default which overwrites scoped config/rbac/role.yaml
# GOFLAGS="-mod=mod" /tmp/tmp.SvlmU2Qpbn/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
GOFLAGS="-mod=mod" /tmp/tmp.SvlmU2Qpbn/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" webhook paths="./..." output:crd:artifacts:config=config/crd/bases
main.go:32:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
main.go:33:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
tests/e2e/lib/apps.go:22:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
tests/e2e/lib/apps.go:23:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
tests/e2e/lib/apps.go:26:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
Error: not all generators ran successfully
run `controller-gen crd:trivialVersions=true,preserveUnknownFields=false webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen crd:trivialVersions=true,preserveUnknownFields=false webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make[1]: *** [Makefile:156: manifests] Error 1
make[1]: Leaving directory '/tmp/tmp.SvlmU2Qpbn'
make: *** [Makefile:371: deploy-olm] Error 2
[whayutin@thinkdoe oadp-operator]$ git branch -a | grep 1.2
* oadp-1.2
  remotes/origin/oadp-1.2
  remotes/origin/v0.1.2
[whayutin@thinkdoe oadp-operator]$ git branch
  foo
  master
* oadp-1.2
[whayutin@thinkdoe oadp-operator]$ git branch -vv
  foo      af6a279 [origin/master: behind 1] OADP-1927: Add unit test for custom BSL and VSL secret (#1023)
  master   3a430a3 [origin/master] OADP-1821: storageClass mapping for data mover volumeOptions (#1006)
* oadp-1.2 8a97b74 [origin/oadp-1.2] oadp-1.2: OADP-1182 - Velero server args in DPA (#1016) (#1020) (#1025)

```

**Comment by kaovilai** [comment]
I think e2e needs fixing with the new moversecuritycontext changes

**Comment by weshayutin** [comment]
this patch worked for me.. thanks @kaovilai looks harmless to merge tbh  :) but ya know

**Comment by kaovilai** [comment]
Don't think it's flake at this point. Something in other repo that merged causing data mover case to fail

**Pull request merged**
