### PR TITLE
oadp-1.2: OADP-2047: Make data mover dummy pod configurable

### PR DESCRIPTION
**Pull request by jmontleon**
cherry-picks #1053

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
`Step operator-e2e-gcp-gather-audit-logs failed after 6s. `
`Step operator-e2e-gcp-e2e succeeded after 1h0m36s. `

/override ci/prow/4.11-operator-e2e-gcp

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
