### PR TITLE
fix: simplify E2E code

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Simplify E2E tests code to do not need call `AddToScheme` more than once. Also, remove unnecessary functions and functions calls.

## How to test the changes made

Run E2E tests or check CI logs and confirm the change did not break or change any behavior.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
They're all failing around `MySQL application two Vol CSI` test

**Review by sseago — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
/override ci/prow/4.16-e2e-test-aws
restore succeeds, but application not working flake

**Pull request merged**
