### PR TITLE
oadp-1.1: privileged movers e2e

### LINKED ISSUE #961: oadp-1.1 data mover e2e needs to set `volsync.backube/privileged-movers` on openshift-adp namespace
Readings
https://volsync.readthedocs.io/en/latest/usage/permissionmodel.html#controlling-mover-permissions
https://hackmd.io/VMopVVDZQbanCbGn6PSl3g

essentially
```
oc annotate --overwrite namespace/openshift-adp volsync.backube/privileged-movers='true'
```

can be done in golang using client libraries.

### PR DESCRIPTION
**Pull request by kaovilai**
- bucket_controller: UpdateOptions -> SubResourceUpdateOptions
- volsync privileged movers, up go.mod, remove ginkgo v1
- fix ginkgo install
- test ginkgo can build in unit tests
- minor dpa bundle updates
- general formatting

Fixes #961

### CODE REVIEW

**Comment by kaovilai** [comment]
```
Failed to compile e2e:
# sigs.k8s.io/controller-runtime/pkg/cache
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/cache/informer_cache.go:144:9: cannot use i.Informer (variable of type "k8s.io/client-go/tools/cache".SharedIndexInformer) as type Informer in return statement:
	"k8s.io/client-go/tools/cache".SharedIndexInformer does not implement Informer (wrong type for AddEventHandler method)
		have AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler) ("k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration, error)
		want AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler)
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/cache/informer_cache.go:158:9: cannot use i.Informer (variable of type "k8s.io/client-go/tools/cache".SharedIndexInformer) as type Informer in return statement:
	"k8s.io/client-go/tools/cache".SharedIndexInformer does not implement Informer (wrong type for AddEventHandler method)
		have AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler) ("k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration, error)
		want AddEventHandler(handler "k8s.io/client-go/tools/cache".ResourceEventHandler)
```

**Comment by kaovilai** [comment]
/retest
install flakes

**Comment by kaovilai** [comment]
/retest
install failures

**Comment by kaovilai** [comment]
After restore, looks like service is not working.
```
Data came from backup-file
 [{"Id":1,"Description":"time to make the donuts","Completed":false},{"Id":3,"Description":"2023-04-17 18:27:22.060652924 +0000 UTC m=+1988.221982725","Completed":false},{"Id":4,"Description":"Monday","Completed":false}]

Data from the response after restore
 <html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style type="text/css">
      body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        line-height: 1.66666667;
        font-size: 16px;
        color: #333;
        background-color: #fff;
        margin: 2em 1em;
      }
      h1 {
        font-size: 28px;
        font-weight: 400;
      }
      p {
        margin: 0 0 10px;
      }
      .alert.alert-info {
        background-color: #F0F0F0;
        margin-top: 30px;
        padding: 30px;
      }
      .alert p {
        padding-left: 35px;
      }
      ul {
        padding-left: 51px;
        position: relative;
      }
      li {
        font-size: 14px;
        margin-bottom: 1em;
      }
      p.info {
        position: relative;
        font-size: 20px;
      }
      p.info:before, p.info:after {
        content: "";
        left: 0;
        position: absolute;
        top: 0;
      }
      p.info:before {
        background: #0066CC;
        border-radius: 16px;
        color: #fff;
        content: "i";
        font: bold 16px/24px serif;
        height: 24px;
        left: 0px;
        text-align: center;
        top: 4px;
        width: 24px;
      }

      @media (min-width: 768px) {
        body {
          margin: 6em;
        }
      }
    </style>
  </head>
  <body>
    <div>
      <h1>Application is not available</h1>
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>

      <div class="alert alert-info">
        <p class="info">
          Possible reasons you are seeing this page:
        </p>
        <ul>
          <li>
            <strong>The host doesn't exist.</strong>
            Make sure the hostname was typed correctly and that a route matching this hostname exists.
          </li>
          <li>
            <strong>The host exists, but doesn't have a matching path.</strong>
            Check if the URL path was typed correctly and that the route was created using the desired path.
          </li>
          <li>
            <strong>Route and path matches, but all pods are down.</strong>
            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>
```

**Comment by kaovilai** [comment]
```
```

**Review by eemcmullan — APPROVED** [review]

**Pull request merged**
