### PR TITLE
fix: CI check go dependencies

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

Fixes https://github.com/openshift/oadp-operator/issues/1369

## How the changes were made

Created make command that will check if `go mod tidy` and `go mod verify` were run.

## How to test the changes made

Test new command, running `make check-go-dependencies` or `make test`

### CODE REVIEW

**Review by kaovilai — DISMISSED** [review]

**Review by shubham-pampattiwar — DISMISSED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
