### PR TITLE
OADP-4819: Add OKE as valid-subscription

### PR DESCRIPTION
**Pull request by rayfordj**
https://issues.redhat.com/browse/OADP-4819

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
Need to do changes in PROW for this to pass, because of ARM. My bad

Is this urgent?

**Comment by rayfordj** [comment]
> Need to do changes in PROW for this to pass, because of ARM. My bad
> 
> Is this urgent?

At the moment, no, 1.3 is not urgent.  It is, I believe, mid-November planned, so we have time here.

**Comment by mateusoliveira43** [comment]
@rayfordj alright

once I have time I create a PR in PROW to fix this and unblock us

**Comment by mateusoliveira43** [comment]
to unblock this PR https://github.com/openshift/release/pull/56496

**Pull request merged**
