### PR TITLE
OADP-1931: Update description in CSV (#1008)

### PR DESCRIPTION
**Pull request by rayfordj**
[OADP-1931](https://issues.redhat.com/browse/OADP-1931) Improve Cluster Service Version YAML's Description fields

Incorporate feedback from [comment](https://issues.redhat.com/browse/OADP-1931?focusedId=22320719&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22320719)

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
/lgtm

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
