### PR TITLE
Update image tags to oadp-1.2 in csv

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**

### CODE REVIEW

**Comment by kaovilai** [comment]
Change config/ then `make bundle`

Also change default in go files would be great

**Comment by sseago** [comment]
This also needs to be changed in config/manager/manager.yaml, controllers/velero_test.go, pkg/common/common.go, ./pkg/credentials/credentials_test.go

**Comment by shubham-pampattiwar** [comment]
@sseago @kaovilai Updated the PR, PTAL, Thank you !

**Comment by kaovilai** [comment]
Let's get e2e running to validate before merging

**Review by weshayutin — APPROVED** [review]

**Review by rayfordj — APPROVED** [review]
/lgtm

**Review by kaovilai — APPROVED** [review]
k fine.. no e2e test today 😷

**Pull request merged**
