### PR TITLE
[oadp-1.4] OADP-3504: imagePullPolicy based on image having or not digest

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Why the changes were made

cherry picked from commit https://github.com/openshift/oadp-operator/commit/93be41ae23bd20f749178f7e7d9c93821796c5d0 : PR https://github.com/openshift/oadp-operator/pull/1397

## How to test the changes made

Follow instructions from parent PR.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
/retest
terminating timeout

**Review by kaovilai — APPROVED** [review]

**Review by mpryc — APPROVED** [review]

**Pull request merged**
