### PR TITLE
Correct indentation re:PSA policy warnings

### PR DESCRIPTION
**Pull request by hhpatel14**

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
Thank you!

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by shawn-hurley — COMMENTED** [review]
VISACK LGTM

**Comment by kaovilai** [comment]
Don't think 4.10 is flake. Something broke 4.10
```
deployment not available with condition: pods "mysql-6895cb4687-rfscd" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/mysql: Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by user or serviceaccount provider "nonroot": Forbidden: not usable by user or serviceaccount provider "volsync-privileged-mover": Forbidden: not usable by user or serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount provider "hostnetwork": Forbidden: not usable by user or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount provider "mongo-persistent-scc": Forbidden: not usable by user or serviceaccount pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/mysql: Forbidden: seccomp may not be set provider "node-exporter": Forbidden: not usable by user or serviceaccount provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by kaovilai** [comment]
this won't pass ci till we fix scc. do not retest the current commit :)
```
  deployment not available with condition: pods "mysql-6895cb4687-vv8g2" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/mysql: Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by user or serviceaccount provider "nonroot": Forbidden: not usable by user or serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount provider "hostnetwork": Forbidden: not usable by user or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount provider "mongo-persistent-scc": Forbidden: not usable by user or serviceaccount pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/mysql: Forbidden: seccomp may not be set provider "node-exporter": Forbidden: not usable by user or serviceaccount provider "privileged": Forbidden: not usable by user or serviceaccount]
  deployment not available with condition: ReplicaSet "mysql-6895cb4687" has timed out progressing.
```
[src](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oadp-operator/1130/pull-ci-openshift-oadp-operator-master-4.10-operator-e2e-aws/1705724204998987776#1:build-log.txt%3A1115)

**Comment by mateusoliveira43** [comment]
@kaovilai do you know why some E2E passed?

**Comment by kaovilai** [comment]
> do you know why some E2E passed?

The PSA policy here was made with newer OCP versions in mind. That meant we need a different solution for 4.10.

**Comment by mateusoliveira43** [comment]
Adding a comment to the application Yaml telling that it only works in 4.11 or higher versions and waiting until 4.14 is out (assuming we will be testing master against latest 4 minor releases of OCP) to merge this PR is a viable option?

**Comment by kaovilai** [comment]
#### Options
- Disable OCP 4.10 CI on master
- Comment this yaml is only for 4.11+ and Update e2e .go to use a different yaml for 4.10

**Comment by shubham-pampattiwar** [comment]
@kaovilai Isn't it time to enable OCP 4.13 CI tests on master and disable OCP 4.10 tests, given our n-2 support policy, n being the latest OCP version.

**Comment by kaovilai** [comment]
> Isn't it time to enable OCP 4.13 CI tests on master

defer to @weshayutin

**Comment by weshayutin** [comment]
> > Isn't it time to enable OCP 4.13 CI tests on master
> 
> defer to @weshayutin

lolz.. like 8 months ago.

**Comment by kaovilai** [comment]
https://github.com/openshift/release/pull/42217
https://github.com/openshift/release/pull/42107

added to 1.2, not master

**Comment by kaovilai** [comment]
/test 4.13-operator-e2e-aws

can ignore 4.10 and remove for master

**Comment by kaovilai** [comment]
/override ci/prow/4.12-operator-e2e-gcp
/override ci/prow/4.10-operator-e2e-gcp
/override ci/prow/4.10-operator-e2e-azure
/override ci/prow/4.10-operator-e2e-aws

re: slack
> [Kill 4.10](https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1696271702923539?thread_ts=1696271594.644719&cid=C0144ECKUJ0)

**Pull request merged**
