### PR TITLE
fix: Remove 1.3 code from master branch

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Now that 1.3 branch is created, remove code related to it form master branch.

### Related issues

Fixes https://github.com/openshift/oadp-operator/issues/1195
Fixes https://github.com/openshift/oadp-operator/issues/1192

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
code freeze?
/hold

**Comment by mateusoliveira43** [comment]
do you want to also fix this issue https://github.com/openshift/oadp-operator/issues/1176 in this PR?

**Comment by kaovilai** [comment]
With 1.3 branch, 1.3 related freeze do not impact master branch

**Comment by kaovilai** [comment]
another ack and lgtm from another eyes

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
`Step operator-e2e-aws-e2e succeeded after 1h4m4s. `
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oadp-operator/1232/pull-ci-openshift-oadp-operator-master-4.13-operator-e2e-aws/1729210661155639296#1:build-log.txt%3A77

prow teardown flake. e2e was green.
/override ci/prow/4.13-operator-e2e-aws

**Pull request merged**
