### PR TITLE
DO NOT MERGE, Test CI

### PR DESCRIPTION
**Pull request by weshayutin**

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
@weshayutin can we close this?
AWS failure was the flake after restore (restore succeeds, but things do not work after, which I tried to attack since last year); AZURE was just infra, failed to create cluster

**Comment by weshayutin** [comment]
@mateusoliveira43 I will close this PR, but not quite yet :) I will use this to access the current state of ci

**Comment by mateusoliveira43** [comment]
@weshayutin is not better to keep track of periodic jobs instead of a PR?

**Comment by kaovilai** [comment]
periodic jobs run once per day. this ci job wesley can trigger whenever as he please.

**Pull request closed without merging**
