### PR TITLE
Fix 3 CSI Volumes sample app deployment issue

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**

### CODE REVIEW

**Review by hhpatel14 — APPROVED** [review]

**Review by eemcmullan — APPROVED** [review]

**Review by weshayutin — CHANGES_REQUESTED** [review]
why provide the command and not have the manifest yaml to update the change as part of the template? No one is going to read that.
-1

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
> why provide the command and not have the manifest yaml to update the change

I guess it isn't always needed??

**Comment by shubham-pampattiwar** [comment]
@kaovilai @weshayutin yes this command is not always needed, we only the issue for OCP 4.10 AFAIK.

**Comment by weshayutin** [comment]
@shubham-pampattiwar does applying the template in 4.11+ do anything negative?

**Pull request merged**
