### PR TITLE
[oadp-1.3] Unsupported server args

### PR DESCRIPTION
**Pull request by mpryc**
## Why the changes were made

cherry picked from commit https://github.com/openshift/oadp-operator/commit/bc1bbe8d55f092c391b3183ea1e94e7cec0b2a43 : PR https://github.com/openshift/oadp-operator/pull/1430

## How to test the changes made

Follow instructions from parent PR.

### CODE REVIEW

**Comment by mpryc** [comment]
/hold

First the cherry-pick #1453 needs to be merged.

**Review by kaovilai — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
/lgtm

**Comment by mateusoliveira43** [comment]
this PR doe not need to be updated prior to merging? To only change some files

**Pull request merged**
