### PR TITLE
CI: Split up E2E test's runBackupAndRestore in preparation for virtualization tests.

### PR DESCRIPTION
**Pull request by mrnold**
Extract the common code factoring from #1333 to its own pull request. This should not create any functional change, but it should make it much easier to review a new VM testing pull request.

### CODE REVIEW

**Comment by kaovilai** [comment]
/override ci/prow/4.12-e2e-test-aws 
/override ci/prow/4.14-e2e-test-azure 

these are flakes

**Review by mpryc — APPROVED** [review]
/lgtm

**Review by weshayutin — DISMISSED** [review]

**Comment by weshayutin** [comment]
@mrnold remember we can override if needed https://github.com/openshift/oadp-operator/blob/master/OWNERS

**Pull request merged**
