### PR TITLE
oadp-1.4: Use ubi9-v1.22.2 in Containerfiles

### PR DESCRIPTION
**Pull request by kaovilai**
## Why the changes were made

Use ubi9-v1.22.2 in Containerfiles

## How to test the changes made

`podman build .`

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
need to update here as well? 
https://github.com/openshift/oadp-operator/blob/902257d4c59184cb439f61fc2450ea66fd24afd5/build/ci-Dockerfile#L2

**Comment by kaovilai** [comment]
Sure can't hurt.

**Comment by mateusoliveira43** [comment]
from unit test failure, I think controller-gen needs to be update here to CI to pass

**Comment by kaovilai** [comment]
conflicts with: https://github.com/openshift/oadp-operator/pull/1398 but should be ok.
so will update c-gen anyway

**Comment by mateusoliveira43** [comment]
also may need to update `CRD_OPTIONS ?= "crd"` in Makefile

**Comment by kaovilai** [comment]
> also may need to update `CRD_OPTIONS ?= "crd"` in Makefile

will do according to https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1716913747326549 if it fails.

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
update `CRD_OPTIONS` in Makefile to CI to pass

**Comment by kaovilai** [comment]
Closing since I got the ocp/release PRs in already. Let's focus on getting #1398 working

**Pull request closed without merging**
