### PR TITLE
pod dns config

### LINKED ISSUE #269: Velero pod DNS config support
Support DNS configs for Velero pod.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

### PR DESCRIPTION
**Pull request by kaovilai**
closes #269

### CODE REVIEW

**Comment by dymurray** [comment]
This looks good so far, can we add tests like you did for pod annotations please?

**Comment by kaovilai** [comment]
> This looks good so far, can we add tests like you did for pod annotations please?

Done!

**Review by dymurray — APPROVED** [review]

**Pull request merged**
